/**
 * Removes Android's default autofill highlight from text inputs.
 *
 * When Google Password Manager fills a field, Android paints
 * `android:autofilledHighlight` over it — a translucent Material yellow.
 * On Rootaroo's dark ground (#0B1220) that renders as a muddy khaki wash
 * across the email/password inputs, and it can't be styled from React
 * Native because it's drawn by the native EditText, not by the RN view.
 *
 * Setting it transparent keeps autofill (and password-manager support)
 * fully working while letting the app's own field styling show through.
 * Theme-level, so it applies to every input in the app at once.
 *
 * Lives here rather than in android/app/src/main/res/values/styles.xml
 * because /android is gitignored and regenerated by `expo prebuild`.
 */
const { withAndroidStyles } = require('expo/config-plugins');

const ATTR = 'android:autofilledHighlight';

module.exports = function withAutofillHighlight(config) {
  return withAndroidStyles(config, (cfg) => {
    const styles = cfg.modResults?.resources?.style;
    if (!Array.isArray(styles)) return cfg;

    const appTheme = styles.find((s) => s?.$?.name === 'AppTheme');
    if (!appTheme) return cfg;

    // Idempotent — prebuild may run this against an already-patched theme.
    appTheme.item = (appTheme.item || []).filter((i) => i?.$?.name !== ATTR);
    appTheme.item.push({
      _: '@android:color/transparent',
      // The attribute is API 26+; older devices ignore it at runtime, and
      // this keeps the lint check quiet at build time.
      $: { name: ATTR, 'tools:targetApi': '26' },
    });

    return cfg;
  });
};
